formatter: markdown table

version:

header-from: 
footer-from: USAGE.md

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

content:

output:
  file:
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from:

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
